# Self signed certificates generated by the ssl-cert package
# Don't use them in a production server!
# Use this two manual
#ssl_certificate /etc/letsencrypt/live/internal.elhobbiton.com/fullchain.pem;
#ssl_certificate_key /etc/letsencrypt/live/internal.elhobbiton.com/privkey.pem;
ssl_prefer_server_ciphers on;
ssl_ecdh_curve secp384r1;
ssl_session_cache shared:SSL:10m;
ssl_session_tickets off;
ssl_stapling on;
ssl_stapling_verify on;
resolver 8.8.8.8 8.8.4.4 valid=300s;
resolver_timeout 5s;
ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';
ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
ssl_dhparam dhparam.pem;

# Its a pain in dev
#add_header Strict-Transport-Security "max-age=63072000; includeSubdomains";
add_header X-Frame-Options DENY;
add_header X-Content-Type-Options nosniff;
